version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wordly
    networks:
        - wordly-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
        - wordly-network

  wordly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://postgres:root@postgres/wordly"
    networks:
      - wordly-network

volumes:
    data:

networks:
    wordly-network: