name: Deploy app
on:
  push:
    branches:
      - main

env:
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  _GITHUB_ID: ${{ secrets._GITHUB_ID }}
  _GITHUB_SECRET: ${{ secrets._GITHUB_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  deploy:
    name: Deploy app
    runs-on: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        run: touch .env && echo "GOOGLE_ID=$GOOGLE_ID\nGOOGLE_SECRET=$GOOGLE_SECRET\n_GITHUB_ID=$_GITHUB_ID\n_GITHUB_SECRET=$_GITHUB_SECRET\nAUTH_SECRET=$AUTH_SECRET" > .env && docker-compose up -d
