name: Deploy app
on:
  push:
    branches:
      - main

env:
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  _GITHUB_ID: ${{ secrets._GITHUB_ID }}
  _GITHUB_SECRET: ${{ secrets._GITHUB_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  setup-data-folder:
    name: Setup data folder
    runs-on: prod
    continue-on-error: true
    steps:
      - name: create data directory
        run: mkdir ~/data
      - name: change permissions
        run: chmod -R go+w ~/data

  setup-minio-folder:
    name: Setup minio folder
    runs-on: prod
    continue-on-error: true
    steps:
      - name: create minio directory
        run: mkdir ~/minio

  create-env-file:
    name: Create env file
    runs-on: prod
    steps:
      - name: create env file
        run: touch .env
      - name: write to env file
        run: echo -e "GOOGLE_ID=$GOOGLE_ID\nGOOGLE_SECRET=$GOOGLE_SECRET\n_GITHUB_ID=$_GITHUB_ID\n_GITHUB_SECRET=$_GITHUB_SECRET\nAUTH_SECRET=$AUTH_SECRET

  deploy:
    name: Deploy app
    runs-on: prod
    needs: [setup-data-folder, setup-minio-folder, create-env-file]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        run:  docker-compose up -d
