name: Deploy app
on:
  push:
    branches:
      - main
env:
  GOOGLE_ID=${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
  GITHUB_ID=${{ secrets._GITHUB_ID }}
  GITHUB_SECRET=${{ secrets._GITHUB_SECRET }}
jobs:
  deploy:
    name: Deploy app
    runs-on: prod
    steps:
      - name: deploy
        run: touch .env && docker-compose up -d --build -e GOOGLE_ID=$GOOGLE_ID -e GOOGLE_SECRET=$GOOGLE_SECRET -e GITHUB_ID=$GITHUB_ID -e GITHUB_SECRET=$GITHUB_SECRET
